### ISSUE TITLE
Hide all names/tripcodes/IDs

### ISSUE THREAD

**Issue by ricewind012** [saxamaphone69/ss16#20]
What is the point of keeping this option if 4chan X has already got a forced anonymisation option ?

**Comment by saxamaphone69** [comment]
1. It gets rid of the `Anonymous` that 4chan X would normally add.
2. Just another way/option to do it.

I need to redo the styling for how it's done and make some on-hover options to show details because lately my habits make me pay no mind to names or trips, and when the option in `ss21` is enabled the "watch thread" and "2 minutes ago" is too together.

**Comment by saxamaphone69** [comment]
Actually, reopening to remind myself to do it during the holidays when I inevitably update everything for 2023.
